feat: convert project to typescript, add types
wethegit/react-marquee pull request #64
Opened 2024-07-30 19:56 UTC by wonderfulfrog

## Description

This PR updates the project to use TypeScript, and include type definitions when importing the module in other projects.

The node version was also bumped to `20.16.0`, which is the current LTS version.

I did my best to break up each change into smaller commits to follow the flow of my changes. I borrowed a few files from `wethegit/react-modal` to make things easier (e.g. `utils/classnames.ts`).

## Notes

There is a warning about different versions of TypeScript when building the project:

```sh
$ npm run build
// Output truncated
Analysis will use the bundled TypeScript version 5.4.2
*** The target project appears to use TypeScript 5.5.4 which is newer than the bundled compiler engine; consider upgrading API Extractor.
```

There aren't any build errors as a result of this warning. [There is a PR open](https://github.com/microsoft/rushstack/pull/4815) that updates TypeScript to 5.5 for [API Extractor](https://github.com/microsoft/rushstack/tree/main/apps/api-extractor). I believe once that PR is merged the warning will disappear.

2024-07-30 21:35 UTC, marlonmarcello requested changes
Great work @wonderfulfrog !

I'd advice to test this locally in an external project by using `npm link`.

Just to make sure the build and the types output are as expected.

2024-07-30 21:35 UTC, marlonmarcello commented on src/lib/marquee.tsx
> +export interface MarqueeProps extends React.Component {
This is bit more forgiving as it allows users of the component to pass any valid HTML attribute that a `div` can have.

Important as you can then pass `data-` and `aria-` attributes as needed.

```suggestion
export interface MarqueeProps extends React.ComponentPropsWithoutRef<"div"> {
```

2024-07-30 21:35 UTC, marlonmarcello commented on src/lib/marquee.tsx
> +  className: string
If you accept the suggestion above these become redundant.

```suggestion
```

2024-07-30 21:53 UTC, marlonmarcello requested changes

2024-07-30 21:53 UTC, marlonmarcello commented on vite.config.ts
@wonderfulfrog while you are at it, can you please update the rollupOption to also externalize the react runtime like we have here on rect-modal please?
https://github.com/wethegit/react-modal/blob/main/vite.config.ts#L19

2024-07-30 22:17 UTC, wonderfulfrog commented on vite.config.ts
@marlonmarcello Did you also want me to include `"react-dom": "ReactDOM",` as part of the `globals` option?

2024-07-30 22:19 UTC, andrewrubin reviewed
Looks great @wonderfulfrog, thanks for taking the time to do this 👏

2024-07-30 23:09 UTC, marlonmarcello commented on vite.config.ts
Yes please 🙏

2024-07-31 00:17 UTC, wonderfulfrog commented on vite.config.ts
I added the "react/jsx-runtime" to the external array, like in `react-modal`. It created a warning though, until I added it was part of the `globals` property. Let me know if this is okay or if we should change it.

2024-07-31 16:53 UTC, marlonmarcello commented on vite.config.ts
That's correct, it's exactly how the react-modal one

2024-07-31 18:42 UTC, wonderfulfrog commented
Using `npm link`, I can confirm the latest revision of the build works with a fresh Next.js project.

A fresh corgi project is having issues. It might be a corgi-specific problem, I'm not sure. Here is an error log I'm getting:
![image](https://github.com/user-attachments/assets/7a7b0512-ab75-4145-bd94-6211ecfdef48)

```
TypeError: Cannot read properties of null (reading 'useState')
```

![image](https://github.com/user-attachments/assets/00ea21c2-837b-48ef-8c41-5e39129b630c)
```
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

2024-07-31 22:05 UTC, marlonmarcello commented
The `corgi` issue is really weird and I have a feeling it might have to do with `npm link`

2024-07-31 22:06 UTC, marlonmarcello approved these changes

2024-08-01 17:03 UTC, marlonmarcello approved these changes

2024-08-01 17:03 UTC, merged